{
 "title": "Boutique",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "NGINX Ingress 95th Percentile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frontend Ingress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress =~ \"frontend-ingress\"}[10s])))\n"
    }
   ]
  },
  { "title": "Service Connection Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ad Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"adservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Cart Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"cartservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Checkout Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"checkoutservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Currency Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"currencyservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Email Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"emailservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Payment Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"paymentservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Product Catalog Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"productcatalogservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Recommendation Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"recommendationservice\"}[30s]))"
    }
   ]
  },
  {
   "title": "Shipping Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(boutique_tcp_port_established_connections_total{job =~ \"shippingservice\"}[30s]))"
    }
   ]
  }
 ]
}