#!/usr/bin/env bash
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Local variables for multipass-rke2
#
# Author(s): Sebastiaan van Steenis
#            Justin Cook

## Configurable settings
# Name for the cluster/configuration files
NAME=""
# Ubuntu image to use (xenial/bionic/focal/jammy)
IMAGE="jammy"
# RKE2 channel
RKE2_CHANNEL="stable"
# RKE2 version
#RKE2_VERSION="v1.24.12+rke2r1"
#RKE2_VERSION="v1.25.8+rke2r1"
# How many master nodes to create
MASTER_NODE_COUNT="1"
# How many compute nodes to create
AGENT_NODE_COUNT="3"
# How many CPUs to allocate to each machine
MASTER_NODE_CPU="2"
AGENT_NODE_CPU="2"
# How much disk space to allocate to each master and compute node
MASTER_DISK_SIZE="20G"
AGENT_DISK_SIZE="40G"
# How much memory to allocate to each machine
MASTER_MEMORY_SIZE="4G"
AGENT_MEMORY_SIZE="8G"
# Preconfigured secret to join the cluster (or autogenerated if empty)
# Note: in order to use this script multiple times to add nodes, this needs
# to be configured.
TOKEN=""
# Hostnames or IPv4/IPv6 addresses as Subject Alternative Names on the server
# TLS cert
TLSSAN="rancher.test"
## End configurable settings
# Where to store the rke2 cluster kubeconfig
LOCALKUBECONFIG="${HOME}/.kube/config-${NAME}"

if [ -n "${RKE2_VERSION:-}" ]
then
    CLOUD_INIT_INSTALL="INSTALL_RKE2_VERSION=${RKE2_VERSION}"
else
    CLOUD_INIT_INSTALL="INSTALL_RKE2_CHANNEL=${RKE2_CHANNEL}"
fi

# Set KUBECTLCMD to local binary if found in PATH. Otherwise, use the the
# Multipass primary master.
if command -v kubectl >/dev/null 2>&1
then
    KUBECTLCMD="$(command -v kubectl)"
else
    KUBECTLCMD="${MULTIPASSCMD} exec ${NAME}-rke2-master-1 -- /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml"
fi
