apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: conntrack-network-init-image
  labels:
    app: conntrack-network-init-image
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/jhcook/kubernetes-dev-env.git"
      ref: "devel"
    contextDir: "hpa/sidecar/conntrack-network-init"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: conntrack-network-init:latest