kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/display-name: conntrack-network-init
  name: conntrack-network-init
  namespace: default
spec:
  lookupPolicy:
    local: true