kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/display-name: tcp-exporter
  name: tcp-exporter
  namespace: default
spec:
  lookupPolicy:
    local: true
